name: Test Automation workflow

on:
  schedule:
    - cron: 45 16 * * *
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Running test automation framework with maven
      run: mvn test -X -Dbrowser="chrome" -DisLambdaTest="false" -DisHeadless="true"

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: Test logs
        path: logs/

    - name: Upload Screenshot as artifacts
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: screenshots
        path: screenshots/

    - name: Upload HTML Reports as artifacts
      if: always()
      uses: actions/upload-artifact@v7.0.1
      with:
        name: html-report
        path: reporter/Index.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"

    - name: Copy Report to gh-pages folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R reporter/Index.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

        - name: Deploy
          if: always()
          uses: JamesIves/github-pages-deploy-action@v4.8.0
          with:
            folder: public/extent-reports
            token: ${{secrets.PAT}}
            clean: true


      
    

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
